apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spa-demo-data
  namespace: spa-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: ${spa_demo_storage_size}
