apiVersion: v1
kind: Secret
metadata:
  name: spa-demo-db
  namespace: spa-demo
type: Opaque
stringData:
  DB_HOST: ${spa_demo_db_endpoint}
  DB_PORT: "5432"
  DB_NAME: ${spa_demo_db_name}
  DB_USER: ${spa_demo_db_username}
  DB_PASSWORD: ${spa_demo_db_password}
  PORT: "3000"
  NODE_ENV: production
