splunk-otel-collector:
  distribution: eks
  cloudProvider: aws
  clusterName: ""

  splunkObservability:
    realm: "us1"
    accessToken: ""
    profilingEnabled: true

  splunkPlatform:
    endpoint: ""
    token: ""
    logsEnabled: true
    metricsEnabled: false
    tracesEnabled: false

  secret:
    create: false
    name: "signalfx-otel-credentials"

  gateway:
    enabled: false

  agent:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
