apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: splunk-otel-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://signalfx.github.io/splunk-otel-collector-chart
