distribution: eks
cloudProvider: aws
clusterName: ${splunk_otel_cluster_name}

splunkObservability:
  realm: ${splunk_observability_realm}
  accessToken: ${splunk_observability_access_token}
  profilingEnabled: false

splunkPlatform:
  endpoint: ${splunk_platform_endpoint}
  token: ${splunk_platform_token}
  logsEnabled: true
  metricsEnabled: false
  tracesEnabled: false

gateway:
  enabled: false

agent:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
