apiVersion: v1
kind: Service
metadata:
  name: spa-demo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: spa-demo
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
