apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-spa-demo
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-kube-system
  interval: 10m
  path: ./kubernetes/apps/spa-demo/deploy/overlays/default
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
        optional: true
